spring:
    application:
        name: fundamentos01
    datasource:
        url: jdbc:postgresql://localhost:5432/devdb
        username: ups
        password: ups123
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                '[format_sql]': true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                '[use_sql_comments]': true
logging:
    level:
        '[org.hibernate.SQL]': DEBUG
        '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
        '[org.springframework.jdbc.core]': DEBUG
server:
    port: 8080
